//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEngine;

namespace Chromatic {

    public static partial class ColorMaps {


        public static Gradient magma {
            get {
                if (_magma == null) {
                    _magma = new Gradient();
                    _magma.SetKeys(magmaArray, null);
                }
                return _magma;
            }
        }
        private static Gradient _magma;
        
        public static Gradient inferno {
            get {
                if (_inferno == null) {
                    _inferno = new Gradient();
                    _inferno.SetKeys(infernoArray, null);
                }
                return _inferno;
            }
        }
        private static Gradient _inferno;
        
        public static Gradient plasma {
            get {
                if (_plasma == null) {
                    _plasma = new Gradient();
                    _plasma.SetKeys(plasmaArray, null);
                }
                return _plasma;
            }
        }
        private static Gradient _plasma;
        
        public static Gradient viridis {
            get {
                if (_viridis == null) {
                    _viridis = new Gradient();
                    _viridis.SetKeys(viridisArray, null);
                }
                return _viridis;
            }
        }
        private static Gradient _viridis;
        
        public static Gradient cividis {
            get {
                if (_cividis == null) {
                    _cividis = new Gradient();
                    _cividis.SetKeys(cividisArray, null);
                }
                return _cividis;
            }
        }
        private static Gradient _cividis;
        
        public static Gradient twilight {
            get {
                if (_twilight == null) {
                    _twilight = new Gradient();
                    _twilight.SetKeys(twilightArray, null);
                }
                return _twilight;
            }
        }
        private static Gradient _twilight;
        
        public static Gradient twilight_shifted {
            get {
                if (_twilight_shifted == null) {
                    _twilight_shifted = new Gradient();
                    _twilight_shifted.SetKeys(twilight_shiftedArray, null);
                }
                return _twilight_shifted;
            }
        }
        private static Gradient _twilight_shifted;
        
        public static Gradient turbo {
            get {
                if (_turbo == null) {
                    _turbo = new Gradient();
                    _turbo.SetKeys(turboArray, null);
                }
                return _turbo;
            }
        }
        private static Gradient _turbo;
        
        public static Gradient Blues {
            get {
                if (_Blues == null) {
                    _Blues = new Gradient();
                    _Blues.SetKeys(BluesArray, null);
                }
                return _Blues;
            }
        }
        private static Gradient _Blues;
        
        public static Gradient BrBG {
            get {
                if (_BrBG == null) {
                    _BrBG = new Gradient();
                    _BrBG.SetKeys(BrBGArray, null);
                }
                return _BrBG;
            }
        }
        private static Gradient _BrBG;
        
        public static Gradient BuGn {
            get {
                if (_BuGn == null) {
                    _BuGn = new Gradient();
                    _BuGn.SetKeys(BuGnArray, null);
                }
                return _BuGn;
            }
        }
        private static Gradient _BuGn;
        
        public static Gradient BuPu {
            get {
                if (_BuPu == null) {
                    _BuPu = new Gradient();
                    _BuPu.SetKeys(BuPuArray, null);
                }
                return _BuPu;
            }
        }
        private static Gradient _BuPu;
        
        public static Gradient CMRmap {
            get {
                if (_CMRmap == null) {
                    _CMRmap = new Gradient();
                    _CMRmap.SetKeys(CMRmapArray, null);
                }
                return _CMRmap;
            }
        }
        private static Gradient _CMRmap;
        
        public static Gradient GnBu {
            get {
                if (_GnBu == null) {
                    _GnBu = new Gradient();
                    _GnBu.SetKeys(GnBuArray, null);
                }
                return _GnBu;
            }
        }
        private static Gradient _GnBu;
        
        public static Gradient Greens {
            get {
                if (_Greens == null) {
                    _Greens = new Gradient();
                    _Greens.SetKeys(GreensArray, null);
                }
                return _Greens;
            }
        }
        private static Gradient _Greens;
        
        public static Gradient Greys {
            get {
                if (_Greys == null) {
                    _Greys = new Gradient();
                    _Greys.SetKeys(GreysArray, null);
                }
                return _Greys;
            }
        }
        private static Gradient _Greys;
        
        public static Gradient OrRd {
            get {
                if (_OrRd == null) {
                    _OrRd = new Gradient();
                    _OrRd.SetKeys(OrRdArray, null);
                }
                return _OrRd;
            }
        }
        private static Gradient _OrRd;
        
        public static Gradient Oranges {
            get {
                if (_Oranges == null) {
                    _Oranges = new Gradient();
                    _Oranges.SetKeys(OrangesArray, null);
                }
                return _Oranges;
            }
        }
        private static Gradient _Oranges;
        
        public static Gradient PRGn {
            get {
                if (_PRGn == null) {
                    _PRGn = new Gradient();
                    _PRGn.SetKeys(PRGnArray, null);
                }
                return _PRGn;
            }
        }
        private static Gradient _PRGn;
        
        public static Gradient PiYG {
            get {
                if (_PiYG == null) {
                    _PiYG = new Gradient();
                    _PiYG.SetKeys(PiYGArray, null);
                }
                return _PiYG;
            }
        }
        private static Gradient _PiYG;
        
        public static Gradient PuBu {
            get {
                if (_PuBu == null) {
                    _PuBu = new Gradient();
                    _PuBu.SetKeys(PuBuArray, null);
                }
                return _PuBu;
            }
        }
        private static Gradient _PuBu;
        
        public static Gradient PuBuGn {
            get {
                if (_PuBuGn == null) {
                    _PuBuGn = new Gradient();
                    _PuBuGn.SetKeys(PuBuGnArray, null);
                }
                return _PuBuGn;
            }
        }
        private static Gradient _PuBuGn;
        
        public static Gradient PuOr {
            get {
                if (_PuOr == null) {
                    _PuOr = new Gradient();
                    _PuOr.SetKeys(PuOrArray, null);
                }
                return _PuOr;
            }
        }
        private static Gradient _PuOr;
        
        public static Gradient PuRd {
            get {
                if (_PuRd == null) {
                    _PuRd = new Gradient();
                    _PuRd.SetKeys(PuRdArray, null);
                }
                return _PuRd;
            }
        }
        private static Gradient _PuRd;
        
        public static Gradient Purples {
            get {
                if (_Purples == null) {
                    _Purples = new Gradient();
                    _Purples.SetKeys(PurplesArray, null);
                }
                return _Purples;
            }
        }
        private static Gradient _Purples;
        
        public static Gradient RdBu {
            get {
                if (_RdBu == null) {
                    _RdBu = new Gradient();
                    _RdBu.SetKeys(RdBuArray, null);
                }
                return _RdBu;
            }
        }
        private static Gradient _RdBu;
        
        public static Gradient RdGy {
            get {
                if (_RdGy == null) {
                    _RdGy = new Gradient();
                    _RdGy.SetKeys(RdGyArray, null);
                }
                return _RdGy;
            }
        }
        private static Gradient _RdGy;
        
        public static Gradient RdPu {
            get {
                if (_RdPu == null) {
                    _RdPu = new Gradient();
                    _RdPu.SetKeys(RdPuArray, null);
                }
                return _RdPu;
            }
        }
        private static Gradient _RdPu;
        
        public static Gradient RdYlBu {
            get {
                if (_RdYlBu == null) {
                    _RdYlBu = new Gradient();
                    _RdYlBu.SetKeys(RdYlBuArray, null);
                }
                return _RdYlBu;
            }
        }
        private static Gradient _RdYlBu;
        
        public static Gradient RdYlGn {
            get {
                if (_RdYlGn == null) {
                    _RdYlGn = new Gradient();
                    _RdYlGn.SetKeys(RdYlGnArray, null);
                }
                return _RdYlGn;
            }
        }
        private static Gradient _RdYlGn;
        
        public static Gradient Reds {
            get {
                if (_Reds == null) {
                    _Reds = new Gradient();
                    _Reds.SetKeys(RedsArray, null);
                }
                return _Reds;
            }
        }
        private static Gradient _Reds;
        
        public static Gradient Spectral {
            get {
                if (_Spectral == null) {
                    _Spectral = new Gradient();
                    _Spectral.SetKeys(SpectralArray, null);
                }
                return _Spectral;
            }
        }
        private static Gradient _Spectral;
        
        public static Gradient Wistia {
            get {
                if (_Wistia == null) {
                    _Wistia = new Gradient();
                    _Wistia.SetKeys(WistiaArray, null);
                }
                return _Wistia;
            }
        }
        private static Gradient _Wistia;
        
        public static Gradient YlGn {
            get {
                if (_YlGn == null) {
                    _YlGn = new Gradient();
                    _YlGn.SetKeys(YlGnArray, null);
                }
                return _YlGn;
            }
        }
        private static Gradient _YlGn;
        
        public static Gradient YlGnBu {
            get {
                if (_YlGnBu == null) {
                    _YlGnBu = new Gradient();
                    _YlGnBu.SetKeys(YlGnBuArray, null);
                }
                return _YlGnBu;
            }
        }
        private static Gradient _YlGnBu;
        
        public static Gradient YlOrBr {
            get {
                if (_YlOrBr == null) {
                    _YlOrBr = new Gradient();
                    _YlOrBr.SetKeys(YlOrBrArray, null);
                }
                return _YlOrBr;
            }
        }
        private static Gradient _YlOrBr;
        
        public static Gradient YlOrRd {
            get {
                if (_YlOrRd == null) {
                    _YlOrRd = new Gradient();
                    _YlOrRd.SetKeys(YlOrRdArray, null);
                }
                return _YlOrRd;
            }
        }
        private static Gradient _YlOrRd;
        
        public static Gradient afmhot {
            get {
                if (_afmhot == null) {
                    _afmhot = new Gradient();
                    _afmhot.SetKeys(afmhotArray, null);
                }
                return _afmhot;
            }
        }
        private static Gradient _afmhot;
        
        public static Gradient autumn {
            get {
                if (_autumn == null) {
                    _autumn = new Gradient();
                    _autumn.SetKeys(autumnArray, null);
                }
                return _autumn;
            }
        }
        private static Gradient _autumn;
        
        public static Gradient binary {
            get {
                if (_binary == null) {
                    _binary = new Gradient();
                    _binary.SetKeys(binaryArray, null);
                }
                return _binary;
            }
        }
        private static Gradient _binary;
        
        public static Gradient bone {
            get {
                if (_bone == null) {
                    _bone = new Gradient();
                    _bone.SetKeys(boneArray, null);
                }
                return _bone;
            }
        }
        private static Gradient _bone;
        
        public static Gradient brg {
            get {
                if (_brg == null) {
                    _brg = new Gradient();
                    _brg.SetKeys(brgArray, null);
                }
                return _brg;
            }
        }
        private static Gradient _brg;
        
        public static Gradient bwr {
            get {
                if (_bwr == null) {
                    _bwr = new Gradient();
                    _bwr.SetKeys(bwrArray, null);
                }
                return _bwr;
            }
        }
        private static Gradient _bwr;
        
        public static Gradient cool {
            get {
                if (_cool == null) {
                    _cool = new Gradient();
                    _cool.SetKeys(coolArray, null);
                }
                return _cool;
            }
        }
        private static Gradient _cool;
        
        public static Gradient coolwarm {
            get {
                if (_coolwarm == null) {
                    _coolwarm = new Gradient();
                    _coolwarm.SetKeys(coolwarmArray, null);
                }
                return _coolwarm;
            }
        }
        private static Gradient _coolwarm;
        
        public static Gradient copper {
            get {
                if (_copper == null) {
                    _copper = new Gradient();
                    _copper.SetKeys(copperArray, null);
                }
                return _copper;
            }
        }
        private static Gradient _copper;
        
        public static Gradient cubehelix {
            get {
                if (_cubehelix == null) {
                    _cubehelix = new Gradient();
                    _cubehelix.SetKeys(cubehelixArray, null);
                }
                return _cubehelix;
            }
        }
        private static Gradient _cubehelix;
        
        public static Gradient flag {
            get {
                if (_flag == null) {
                    _flag = new Gradient();
                    _flag.SetKeys(flagArray, null);
                }
                return _flag;
            }
        }
        private static Gradient _flag;
        
        public static Gradient gist_earth {
            get {
                if (_gist_earth == null) {
                    _gist_earth = new Gradient();
                    _gist_earth.SetKeys(gist_earthArray, null);
                }
                return _gist_earth;
            }
        }
        private static Gradient _gist_earth;
        
        public static Gradient gist_gray {
            get {
                if (_gist_gray == null) {
                    _gist_gray = new Gradient();
                    _gist_gray.SetKeys(gist_grayArray, null);
                }
                return _gist_gray;
            }
        }
        private static Gradient _gist_gray;
        
        public static Gradient gist_heat {
            get {
                if (_gist_heat == null) {
                    _gist_heat = new Gradient();
                    _gist_heat.SetKeys(gist_heatArray, null);
                }
                return _gist_heat;
            }
        }
        private static Gradient _gist_heat;
        
        public static Gradient gist_ncar {
            get {
                if (_gist_ncar == null) {
                    _gist_ncar = new Gradient();
                    _gist_ncar.SetKeys(gist_ncarArray, null);
                }
                return _gist_ncar;
            }
        }
        private static Gradient _gist_ncar;
        
        public static Gradient gist_rainbow {
            get {
                if (_gist_rainbow == null) {
                    _gist_rainbow = new Gradient();
                    _gist_rainbow.SetKeys(gist_rainbowArray, null);
                }
                return _gist_rainbow;
            }
        }
        private static Gradient _gist_rainbow;
        
        public static Gradient gist_stern {
            get {
                if (_gist_stern == null) {
                    _gist_stern = new Gradient();
                    _gist_stern.SetKeys(gist_sternArray, null);
                }
                return _gist_stern;
            }
        }
        private static Gradient _gist_stern;
        
        public static Gradient gist_yarg {
            get {
                if (_gist_yarg == null) {
                    _gist_yarg = new Gradient();
                    _gist_yarg.SetKeys(gist_yargArray, null);
                }
                return _gist_yarg;
            }
        }
        private static Gradient _gist_yarg;
        
        public static Gradient gnuplot {
            get {
                if (_gnuplot == null) {
                    _gnuplot = new Gradient();
                    _gnuplot.SetKeys(gnuplotArray, null);
                }
                return _gnuplot;
            }
        }
        private static Gradient _gnuplot;
        
        public static Gradient gnuplot2 {
            get {
                if (_gnuplot2 == null) {
                    _gnuplot2 = new Gradient();
                    _gnuplot2.SetKeys(gnuplot2Array, null);
                }
                return _gnuplot2;
            }
        }
        private static Gradient _gnuplot2;
        
        public static Gradient gray {
            get {
                if (_gray == null) {
                    _gray = new Gradient();
                    _gray.SetKeys(grayArray, null);
                }
                return _gray;
            }
        }
        private static Gradient _gray;
        
        public static Gradient hot {
            get {
                if (_hot == null) {
                    _hot = new Gradient();
                    _hot.SetKeys(hotArray, null);
                }
                return _hot;
            }
        }
        private static Gradient _hot;
        
        public static Gradient hsv {
            get {
                if (_hsv == null) {
                    _hsv = new Gradient();
                    _hsv.SetKeys(hsvArray, null);
                }
                return _hsv;
            }
        }
        private static Gradient _hsv;
        
        public static Gradient jet {
            get {
                if (_jet == null) {
                    _jet = new Gradient();
                    _jet.SetKeys(jetArray, null);
                }
                return _jet;
            }
        }
        private static Gradient _jet;
        
        public static Gradient nipy_spectral {
            get {
                if (_nipy_spectral == null) {
                    _nipy_spectral = new Gradient();
                    _nipy_spectral.SetKeys(nipy_spectralArray, null);
                }
                return _nipy_spectral;
            }
        }
        private static Gradient _nipy_spectral;
        
        public static Gradient ocean {
            get {
                if (_ocean == null) {
                    _ocean = new Gradient();
                    _ocean.SetKeys(oceanArray, null);
                }
                return _ocean;
            }
        }
        private static Gradient _ocean;
        
        public static Gradient pink {
            get {
                if (_pink == null) {
                    _pink = new Gradient();
                    _pink.SetKeys(pinkArray, null);
                }
                return _pink;
            }
        }
        private static Gradient _pink;
        
        public static Gradient prism {
            get {
                if (_prism == null) {
                    _prism = new Gradient();
                    _prism.SetKeys(prismArray, null);
                }
                return _prism;
            }
        }
        private static Gradient _prism;
        
        public static Gradient rainbow {
            get {
                if (_rainbow == null) {
                    _rainbow = new Gradient();
                    _rainbow.SetKeys(rainbowArray, null);
                }
                return _rainbow;
            }
        }
        private static Gradient _rainbow;
        
        public static Gradient seismic {
            get {
                if (_seismic == null) {
                    _seismic = new Gradient();
                    _seismic.SetKeys(seismicArray, null);
                }
                return _seismic;
            }
        }
        private static Gradient _seismic;
        
        public static Gradient spring {
            get {
                if (_spring == null) {
                    _spring = new Gradient();
                    _spring.SetKeys(springArray, null);
                }
                return _spring;
            }
        }
        private static Gradient _spring;
        
        public static Gradient summer {
            get {
                if (_summer == null) {
                    _summer = new Gradient();
                    _summer.SetKeys(summerArray, null);
                }
                return _summer;
            }
        }
        private static Gradient _summer;
        
        public static Gradient terrain {
            get {
                if (_terrain == null) {
                    _terrain = new Gradient();
                    _terrain.SetKeys(terrainArray, null);
                }
                return _terrain;
            }
        }
        private static Gradient _terrain;
        
        public static Gradient winter {
            get {
                if (_winter == null) {
                    _winter = new Gradient();
                    _winter.SetKeys(winterArray, null);
                }
                return _winter;
            }
        }
        private static Gradient _winter;
        
        public static Gradient Accent {
            get {
                if (_Accent == null) {
                    _Accent = new Gradient();
                    _Accent.SetKeys(AccentArray, null);
                }
                return _Accent;
            }
        }
        private static Gradient _Accent;
        
        public static Gradient Dark2 {
            get {
                if (_Dark2 == null) {
                    _Dark2 = new Gradient();
                    _Dark2.SetKeys(Dark2Array, null);
                }
                return _Dark2;
            }
        }
        private static Gradient _Dark2;
        
        public static Gradient Paired {
            get {
                if (_Paired == null) {
                    _Paired = new Gradient();
                    _Paired.SetKeys(PairedArray, null);
                }
                return _Paired;
            }
        }
        private static Gradient _Paired;
        
        public static Gradient Pastel1 {
            get {
                if (_Pastel1 == null) {
                    _Pastel1 = new Gradient();
                    _Pastel1.SetKeys(Pastel1Array, null);
                }
                return _Pastel1;
            }
        }
        private static Gradient _Pastel1;
        
        public static Gradient Pastel2 {
            get {
                if (_Pastel2 == null) {
                    _Pastel2 = new Gradient();
                    _Pastel2.SetKeys(Pastel2Array, null);
                }
                return _Pastel2;
            }
        }
        private static Gradient _Pastel2;
        
        public static Gradient Set1 {
            get {
                if (_Set1 == null) {
                    _Set1 = new Gradient();
                    _Set1.SetKeys(Set1Array, null);
                }
                return _Set1;
            }
        }
        private static Gradient _Set1;
        
        public static Gradient Set2 {
            get {
                if (_Set2 == null) {
                    _Set2 = new Gradient();
                    _Set2.SetKeys(Set2Array, null);
                }
                return _Set2;
            }
        }
        private static Gradient _Set2;
        
        public static Gradient Set3 {
            get {
                if (_Set3 == null) {
                    _Set3 = new Gradient();
                    _Set3.SetKeys(Set3Array, null);
                }
                return _Set3;
            }
        }
        private static Gradient _Set3;
        
        public static Gradient tab10 {
            get {
                if (_tab10 == null) {
                    _tab10 = new Gradient();
                    _tab10.SetKeys(tab10Array, null);
                }
                return _tab10;
            }
        }
        private static Gradient _tab10;
        
        public static Gradient tab20 {
            get {
                if (_tab20 == null) {
                    _tab20 = new Gradient();
                    _tab20.SetKeys(tab20Array, null);
                }
                return _tab20;
            }
        }
        private static Gradient _tab20;
        
        public static Gradient tab20b {
            get {
                if (_tab20b == null) {
                    _tab20b = new Gradient();
                    _tab20b.SetKeys(tab20bArray, null);
                }
                return _tab20b;
            }
        }
        private static Gradient _tab20b;
        
        public static Gradient tab20c {
            get {
                if (_tab20c == null) {
                    _tab20c = new Gradient();
                    _tab20c.SetKeys(tab20cArray, null);
                }
                return _tab20c;
            }
        }
        private static Gradient _tab20c;
        
        public static Gradient magma_r {
            get {
                if (_magma_r == null) {
                    _magma_r = new Gradient();
                    _magma_r.SetKeys(magma_rArray, null);
                }
                return _magma_r;
            }
        }
        private static Gradient _magma_r;
        
        public static Gradient inferno_r {
            get {
                if (_inferno_r == null) {
                    _inferno_r = new Gradient();
                    _inferno_r.SetKeys(inferno_rArray, null);
                }
                return _inferno_r;
            }
        }
        private static Gradient _inferno_r;
        
        public static Gradient plasma_r {
            get {
                if (_plasma_r == null) {
                    _plasma_r = new Gradient();
                    _plasma_r.SetKeys(plasma_rArray, null);
                }
                return _plasma_r;
            }
        }
        private static Gradient _plasma_r;
        
        public static Gradient viridis_r {
            get {
                if (_viridis_r == null) {
                    _viridis_r = new Gradient();
                    _viridis_r.SetKeys(viridis_rArray, null);
                }
                return _viridis_r;
            }
        }
        private static Gradient _viridis_r;
        
        public static Gradient cividis_r {
            get {
                if (_cividis_r == null) {
                    _cividis_r = new Gradient();
                    _cividis_r.SetKeys(cividis_rArray, null);
                }
                return _cividis_r;
            }
        }
        private static Gradient _cividis_r;
        
        public static Gradient twilight_r {
            get {
                if (_twilight_r == null) {
                    _twilight_r = new Gradient();
                    _twilight_r.SetKeys(twilight_rArray, null);
                }
                return _twilight_r;
            }
        }
        private static Gradient _twilight_r;
        
        public static Gradient twilight_shifted_r {
            get {
                if (_twilight_shifted_r == null) {
                    _twilight_shifted_r = new Gradient();
                    _twilight_shifted_r.SetKeys(twilight_shifted_rArray, null);
                }
                return _twilight_shifted_r;
            }
        }
        private static Gradient _twilight_shifted_r;
        
        public static Gradient turbo_r {
            get {
                if (_turbo_r == null) {
                    _turbo_r = new Gradient();
                    _turbo_r.SetKeys(turbo_rArray, null);
                }
                return _turbo_r;
            }
        }
        private static Gradient _turbo_r;
        
        public static Gradient Blues_r {
            get {
                if (_Blues_r == null) {
                    _Blues_r = new Gradient();
                    _Blues_r.SetKeys(Blues_rArray, null);
                }
                return _Blues_r;
            }
        }
        private static Gradient _Blues_r;
        
        public static Gradient BrBG_r {
            get {
                if (_BrBG_r == null) {
                    _BrBG_r = new Gradient();
                    _BrBG_r.SetKeys(BrBG_rArray, null);
                }
                return _BrBG_r;
            }
        }
        private static Gradient _BrBG_r;
        
        public static Gradient BuGn_r {
            get {
                if (_BuGn_r == null) {
                    _BuGn_r = new Gradient();
                    _BuGn_r.SetKeys(BuGn_rArray, null);
                }
                return _BuGn_r;
            }
        }
        private static Gradient _BuGn_r;
        
        public static Gradient BuPu_r {
            get {
                if (_BuPu_r == null) {
                    _BuPu_r = new Gradient();
                    _BuPu_r.SetKeys(BuPu_rArray, null);
                }
                return _BuPu_r;
            }
        }
        private static Gradient _BuPu_r;
        
        public static Gradient CMRmap_r {
            get {
                if (_CMRmap_r == null) {
                    _CMRmap_r = new Gradient();
                    _CMRmap_r.SetKeys(CMRmap_rArray, null);
                }
                return _CMRmap_r;
            }
        }
        private static Gradient _CMRmap_r;
        
        public static Gradient GnBu_r {
            get {
                if (_GnBu_r == null) {
                    _GnBu_r = new Gradient();
                    _GnBu_r.SetKeys(GnBu_rArray, null);
                }
                return _GnBu_r;
            }
        }
        private static Gradient _GnBu_r;
        
        public static Gradient Greens_r {
            get {
                if (_Greens_r == null) {
                    _Greens_r = new Gradient();
                    _Greens_r.SetKeys(Greens_rArray, null);
                }
                return _Greens_r;
            }
        }
        private static Gradient _Greens_r;
        
        public static Gradient Greys_r {
            get {
                if (_Greys_r == null) {
                    _Greys_r = new Gradient();
                    _Greys_r.SetKeys(Greys_rArray, null);
                }
                return _Greys_r;
            }
        }
        private static Gradient _Greys_r;
        
        public static Gradient OrRd_r {
            get {
                if (_OrRd_r == null) {
                    _OrRd_r = new Gradient();
                    _OrRd_r.SetKeys(OrRd_rArray, null);
                }
                return _OrRd_r;
            }
        }
        private static Gradient _OrRd_r;
        
        public static Gradient Oranges_r {
            get {
                if (_Oranges_r == null) {
                    _Oranges_r = new Gradient();
                    _Oranges_r.SetKeys(Oranges_rArray, null);
                }
                return _Oranges_r;
            }
        }
        private static Gradient _Oranges_r;
        
        public static Gradient PRGn_r {
            get {
                if (_PRGn_r == null) {
                    _PRGn_r = new Gradient();
                    _PRGn_r.SetKeys(PRGn_rArray, null);
                }
                return _PRGn_r;
            }
        }
        private static Gradient _PRGn_r;
        
        public static Gradient PiYG_r {
            get {
                if (_PiYG_r == null) {
                    _PiYG_r = new Gradient();
                    _PiYG_r.SetKeys(PiYG_rArray, null);
                }
                return _PiYG_r;
            }
        }
        private static Gradient _PiYG_r;
        
        public static Gradient PuBu_r {
            get {
                if (_PuBu_r == null) {
                    _PuBu_r = new Gradient();
                    _PuBu_r.SetKeys(PuBu_rArray, null);
                }
                return _PuBu_r;
            }
        }
        private static Gradient _PuBu_r;
        
        public static Gradient PuBuGn_r {
            get {
                if (_PuBuGn_r == null) {
                    _PuBuGn_r = new Gradient();
                    _PuBuGn_r.SetKeys(PuBuGn_rArray, null);
                }
                return _PuBuGn_r;
            }
        }
        private static Gradient _PuBuGn_r;
        
        public static Gradient PuOr_r {
            get {
                if (_PuOr_r == null) {
                    _PuOr_r = new Gradient();
                    _PuOr_r.SetKeys(PuOr_rArray, null);
                }
                return _PuOr_r;
            }
        }
        private static Gradient _PuOr_r;
        
        public static Gradient PuRd_r {
            get {
                if (_PuRd_r == null) {
                    _PuRd_r = new Gradient();
                    _PuRd_r.SetKeys(PuRd_rArray, null);
                }
                return _PuRd_r;
            }
        }
        private static Gradient _PuRd_r;
        
        public static Gradient Purples_r {
            get {
                if (_Purples_r == null) {
                    _Purples_r = new Gradient();
                    _Purples_r.SetKeys(Purples_rArray, null);
                }
                return _Purples_r;
            }
        }
        private static Gradient _Purples_r;
        
        public static Gradient RdBu_r {
            get {
                if (_RdBu_r == null) {
                    _RdBu_r = new Gradient();
                    _RdBu_r.SetKeys(RdBu_rArray, null);
                }
                return _RdBu_r;
            }
        }
        private static Gradient _RdBu_r;
        
        public static Gradient RdGy_r {
            get {
                if (_RdGy_r == null) {
                    _RdGy_r = new Gradient();
                    _RdGy_r.SetKeys(RdGy_rArray, null);
                }
                return _RdGy_r;
            }
        }
        private static Gradient _RdGy_r;
        
        public static Gradient RdPu_r {
            get {
                if (_RdPu_r == null) {
                    _RdPu_r = new Gradient();
                    _RdPu_r.SetKeys(RdPu_rArray, null);
                }
                return _RdPu_r;
            }
        }
        private static Gradient _RdPu_r;
        
        public static Gradient RdYlBu_r {
            get {
                if (_RdYlBu_r == null) {
                    _RdYlBu_r = new Gradient();
                    _RdYlBu_r.SetKeys(RdYlBu_rArray, null);
                }
                return _RdYlBu_r;
            }
        }
        private static Gradient _RdYlBu_r;
        
        public static Gradient RdYlGn_r {
            get {
                if (_RdYlGn_r == null) {
                    _RdYlGn_r = new Gradient();
                    _RdYlGn_r.SetKeys(RdYlGn_rArray, null);
                }
                return _RdYlGn_r;
            }
        }
        private static Gradient _RdYlGn_r;
        
        public static Gradient Reds_r {
            get {
                if (_Reds_r == null) {
                    _Reds_r = new Gradient();
                    _Reds_r.SetKeys(Reds_rArray, null);
                }
                return _Reds_r;
            }
        }
        private static Gradient _Reds_r;
        
        public static Gradient Spectral_r {
            get {
                if (_Spectral_r == null) {
                    _Spectral_r = new Gradient();
                    _Spectral_r.SetKeys(Spectral_rArray, null);
                }
                return _Spectral_r;
            }
        }
        private static Gradient _Spectral_r;
        
        public static Gradient Wistia_r {
            get {
                if (_Wistia_r == null) {
                    _Wistia_r = new Gradient();
                    _Wistia_r.SetKeys(Wistia_rArray, null);
                }
                return _Wistia_r;
            }
        }
        private static Gradient _Wistia_r;
        
        public static Gradient YlGn_r {
            get {
                if (_YlGn_r == null) {
                    _YlGn_r = new Gradient();
                    _YlGn_r.SetKeys(YlGn_rArray, null);
                }
                return _YlGn_r;
            }
        }
        private static Gradient _YlGn_r;
        
        public static Gradient YlGnBu_r {
            get {
                if (_YlGnBu_r == null) {
                    _YlGnBu_r = new Gradient();
                    _YlGnBu_r.SetKeys(YlGnBu_rArray, null);
                }
                return _YlGnBu_r;
            }
        }
        private static Gradient _YlGnBu_r;
        
        public static Gradient YlOrBr_r {
            get {
                if (_YlOrBr_r == null) {
                    _YlOrBr_r = new Gradient();
                    _YlOrBr_r.SetKeys(YlOrBr_rArray, null);
                }
                return _YlOrBr_r;
            }
        }
        private static Gradient _YlOrBr_r;
        
        public static Gradient YlOrRd_r {
            get {
                if (_YlOrRd_r == null) {
                    _YlOrRd_r = new Gradient();
                    _YlOrRd_r.SetKeys(YlOrRd_rArray, null);
                }
                return _YlOrRd_r;
            }
        }
        private static Gradient _YlOrRd_r;
        
        public static Gradient afmhot_r {
            get {
                if (_afmhot_r == null) {
                    _afmhot_r = new Gradient();
                    _afmhot_r.SetKeys(afmhot_rArray, null);
                }
                return _afmhot_r;
            }
        }
        private static Gradient _afmhot_r;
        
        public static Gradient autumn_r {
            get {
                if (_autumn_r == null) {
                    _autumn_r = new Gradient();
                    _autumn_r.SetKeys(autumn_rArray, null);
                }
                return _autumn_r;
            }
        }
        private static Gradient _autumn_r;
        
        public static Gradient binary_r {
            get {
                if (_binary_r == null) {
                    _binary_r = new Gradient();
                    _binary_r.SetKeys(binary_rArray, null);
                }
                return _binary_r;
            }
        }
        private static Gradient _binary_r;
        
        public static Gradient bone_r {
            get {
                if (_bone_r == null) {
                    _bone_r = new Gradient();
                    _bone_r.SetKeys(bone_rArray, null);
                }
                return _bone_r;
            }
        }
        private static Gradient _bone_r;
        
        public static Gradient brg_r {
            get {
                if (_brg_r == null) {
                    _brg_r = new Gradient();
                    _brg_r.SetKeys(brg_rArray, null);
                }
                return _brg_r;
            }
        }
        private static Gradient _brg_r;
        
        public static Gradient bwr_r {
            get {
                if (_bwr_r == null) {
                    _bwr_r = new Gradient();
                    _bwr_r.SetKeys(bwr_rArray, null);
                }
                return _bwr_r;
            }
        }
        private static Gradient _bwr_r;
        
        public static Gradient cool_r {
            get {
                if (_cool_r == null) {
                    _cool_r = new Gradient();
                    _cool_r.SetKeys(cool_rArray, null);
                }
                return _cool_r;
            }
        }
        private static Gradient _cool_r;
        
        public static Gradient coolwarm_r {
            get {
                if (_coolwarm_r == null) {
                    _coolwarm_r = new Gradient();
                    _coolwarm_r.SetKeys(coolwarm_rArray, null);
                }
                return _coolwarm_r;
            }
        }
        private static Gradient _coolwarm_r;
        
        public static Gradient copper_r {
            get {
                if (_copper_r == null) {
                    _copper_r = new Gradient();
                    _copper_r.SetKeys(copper_rArray, null);
                }
                return _copper_r;
            }
        }
        private static Gradient _copper_r;
        
        public static Gradient cubehelix_r {
            get {
                if (_cubehelix_r == null) {
                    _cubehelix_r = new Gradient();
                    _cubehelix_r.SetKeys(cubehelix_rArray, null);
                }
                return _cubehelix_r;
            }
        }
        private static Gradient _cubehelix_r;
        
        public static Gradient flag_r {
            get {
                if (_flag_r == null) {
                    _flag_r = new Gradient();
                    _flag_r.SetKeys(flag_rArray, null);
                }
                return _flag_r;
            }
        }
        private static Gradient _flag_r;
        
        public static Gradient gist_earth_r {
            get {
                if (_gist_earth_r == null) {
                    _gist_earth_r = new Gradient();
                    _gist_earth_r.SetKeys(gist_earth_rArray, null);
                }
                return _gist_earth_r;
            }
        }
        private static Gradient _gist_earth_r;
        
        public static Gradient gist_gray_r {
            get {
                if (_gist_gray_r == null) {
                    _gist_gray_r = new Gradient();
                    _gist_gray_r.SetKeys(gist_gray_rArray, null);
                }
                return _gist_gray_r;
            }
        }
        private static Gradient _gist_gray_r;
        
        public static Gradient gist_heat_r {
            get {
                if (_gist_heat_r == null) {
                    _gist_heat_r = new Gradient();
                    _gist_heat_r.SetKeys(gist_heat_rArray, null);
                }
                return _gist_heat_r;
            }
        }
        private static Gradient _gist_heat_r;
        
        public static Gradient gist_ncar_r {
            get {
                if (_gist_ncar_r == null) {
                    _gist_ncar_r = new Gradient();
                    _gist_ncar_r.SetKeys(gist_ncar_rArray, null);
                }
                return _gist_ncar_r;
            }
        }
        private static Gradient _gist_ncar_r;
        
        public static Gradient gist_rainbow_r {
            get {
                if (_gist_rainbow_r == null) {
                    _gist_rainbow_r = new Gradient();
                    _gist_rainbow_r.SetKeys(gist_rainbow_rArray, null);
                }
                return _gist_rainbow_r;
            }
        }
        private static Gradient _gist_rainbow_r;
        
        public static Gradient gist_stern_r {
            get {
                if (_gist_stern_r == null) {
                    _gist_stern_r = new Gradient();
                    _gist_stern_r.SetKeys(gist_stern_rArray, null);
                }
                return _gist_stern_r;
            }
        }
        private static Gradient _gist_stern_r;
        
        public static Gradient gist_yarg_r {
            get {
                if (_gist_yarg_r == null) {
                    _gist_yarg_r = new Gradient();
                    _gist_yarg_r.SetKeys(gist_yarg_rArray, null);
                }
                return _gist_yarg_r;
            }
        }
        private static Gradient _gist_yarg_r;
        
        public static Gradient gnuplot_r {
            get {
                if (_gnuplot_r == null) {
                    _gnuplot_r = new Gradient();
                    _gnuplot_r.SetKeys(gnuplot_rArray, null);
                }
                return _gnuplot_r;
            }
        }
        private static Gradient _gnuplot_r;
        
        public static Gradient gnuplot2_r {
            get {
                if (_gnuplot2_r == null) {
                    _gnuplot2_r = new Gradient();
                    _gnuplot2_r.SetKeys(gnuplot2_rArray, null);
                }
                return _gnuplot2_r;
            }
        }
        private static Gradient _gnuplot2_r;
        
        public static Gradient gray_r {
            get {
                if (_gray_r == null) {
                    _gray_r = new Gradient();
                    _gray_r.SetKeys(gray_rArray, null);
                }
                return _gray_r;
            }
        }
        private static Gradient _gray_r;
        
        public static Gradient hot_r {
            get {
                if (_hot_r == null) {
                    _hot_r = new Gradient();
                    _hot_r.SetKeys(hot_rArray, null);
                }
                return _hot_r;
            }
        }
        private static Gradient _hot_r;
        
        public static Gradient hsv_r {
            get {
                if (_hsv_r == null) {
                    _hsv_r = new Gradient();
                    _hsv_r.SetKeys(hsv_rArray, null);
                }
                return _hsv_r;
            }
        }
        private static Gradient _hsv_r;
        
        public static Gradient jet_r {
            get {
                if (_jet_r == null) {
                    _jet_r = new Gradient();
                    _jet_r.SetKeys(jet_rArray, null);
                }
                return _jet_r;
            }
        }
        private static Gradient _jet_r;
        
        public static Gradient nipy_spectral_r {
            get {
                if (_nipy_spectral_r == null) {
                    _nipy_spectral_r = new Gradient();
                    _nipy_spectral_r.SetKeys(nipy_spectral_rArray, null);
                }
                return _nipy_spectral_r;
            }
        }
        private static Gradient _nipy_spectral_r;
        
        public static Gradient ocean_r {
            get {
                if (_ocean_r == null) {
                    _ocean_r = new Gradient();
                    _ocean_r.SetKeys(ocean_rArray, null);
                }
                return _ocean_r;
            }
        }
        private static Gradient _ocean_r;
        
        public static Gradient pink_r {
            get {
                if (_pink_r == null) {
                    _pink_r = new Gradient();
                    _pink_r.SetKeys(pink_rArray, null);
                }
                return _pink_r;
            }
        }
        private static Gradient _pink_r;
        
        public static Gradient prism_r {
            get {
                if (_prism_r == null) {
                    _prism_r = new Gradient();
                    _prism_r.SetKeys(prism_rArray, null);
                }
                return _prism_r;
            }
        }
        private static Gradient _prism_r;
        
        public static Gradient rainbow_r {
            get {
                if (_rainbow_r == null) {
                    _rainbow_r = new Gradient();
                    _rainbow_r.SetKeys(rainbow_rArray, null);
                }
                return _rainbow_r;
            }
        }
        private static Gradient _rainbow_r;
        
        public static Gradient seismic_r {
            get {
                if (_seismic_r == null) {
                    _seismic_r = new Gradient();
                    _seismic_r.SetKeys(seismic_rArray, null);
                }
                return _seismic_r;
            }
        }
        private static Gradient _seismic_r;
        
        public static Gradient spring_r {
            get {
                if (_spring_r == null) {
                    _spring_r = new Gradient();
                    _spring_r.SetKeys(spring_rArray, null);
                }
                return _spring_r;
            }
        }
        private static Gradient _spring_r;
        
        public static Gradient summer_r {
            get {
                if (_summer_r == null) {
                    _summer_r = new Gradient();
                    _summer_r.SetKeys(summer_rArray, null);
                }
                return _summer_r;
            }
        }
        private static Gradient _summer_r;
        
        public static Gradient terrain_r {
            get {
                if (_terrain_r == null) {
                    _terrain_r = new Gradient();
                    _terrain_r.SetKeys(terrain_rArray, null);
                }
                return _terrain_r;
            }
        }
        private static Gradient _terrain_r;
        
        public static Gradient winter_r {
            get {
                if (_winter_r == null) {
                    _winter_r = new Gradient();
                    _winter_r.SetKeys(winter_rArray, null);
                }
                return _winter_r;
            }
        }
        private static Gradient _winter_r;
        
        public static Gradient Accent_r {
            get {
                if (_Accent_r == null) {
                    _Accent_r = new Gradient();
                    _Accent_r.SetKeys(Accent_rArray, null);
                }
                return _Accent_r;
            }
        }
        private static Gradient _Accent_r;
        
        public static Gradient Dark2_r {
            get {
                if (_Dark2_r == null) {
                    _Dark2_r = new Gradient();
                    _Dark2_r.SetKeys(Dark2_rArray, null);
                }
                return _Dark2_r;
            }
        }
        private static Gradient _Dark2_r;
        
        public static Gradient Paired_r {
            get {
                if (_Paired_r == null) {
                    _Paired_r = new Gradient();
                    _Paired_r.SetKeys(Paired_rArray, null);
                }
                return _Paired_r;
            }
        }
        private static Gradient _Paired_r;
        
        public static Gradient Pastel1_r {
            get {
                if (_Pastel1_r == null) {
                    _Pastel1_r = new Gradient();
                    _Pastel1_r.SetKeys(Pastel1_rArray, null);
                }
                return _Pastel1_r;
            }
        }
        private static Gradient _Pastel1_r;
        
        public static Gradient Pastel2_r {
            get {
                if (_Pastel2_r == null) {
                    _Pastel2_r = new Gradient();
                    _Pastel2_r.SetKeys(Pastel2_rArray, null);
                }
                return _Pastel2_r;
            }
        }
        private static Gradient _Pastel2_r;
        
        public static Gradient Set1_r {
            get {
                if (_Set1_r == null) {
                    _Set1_r = new Gradient();
                    _Set1_r.SetKeys(Set1_rArray, null);
                }
                return _Set1_r;
            }
        }
        private static Gradient _Set1_r;
        
        public static Gradient Set2_r {
            get {
                if (_Set2_r == null) {
                    _Set2_r = new Gradient();
                    _Set2_r.SetKeys(Set2_rArray, null);
                }
                return _Set2_r;
            }
        }
        private static Gradient _Set2_r;
        
        public static Gradient Set3_r {
            get {
                if (_Set3_r == null) {
                    _Set3_r = new Gradient();
                    _Set3_r.SetKeys(Set3_rArray, null);
                }
                return _Set3_r;
            }
        }
        private static Gradient _Set3_r;
        
        public static Gradient tab10_r {
            get {
                if (_tab10_r == null) {
                    _tab10_r = new Gradient();
                    _tab10_r.SetKeys(tab10_rArray, null);
                }
                return _tab10_r;
            }
        }
        private static Gradient _tab10_r;
        
        public static Gradient tab20_r {
            get {
                if (_tab20_r == null) {
                    _tab20_r = new Gradient();
                    _tab20_r.SetKeys(tab20_rArray, null);
                }
                return _tab20_r;
            }
        }
        private static Gradient _tab20_r;
        
        public static Gradient tab20b_r {
            get {
                if (_tab20b_r == null) {
                    _tab20b_r = new Gradient();
                    _tab20b_r.SetKeys(tab20b_rArray, null);
                }
                return _tab20b_r;
            }
        }
        private static Gradient _tab20b_r;
        
        public static Gradient tab20c_r {
            get {
                if (_tab20c_r == null) {
                    _tab20c_r = new Gradient();
                    _tab20c_r.SetKeys(tab20c_rArray, null);
                }
                return _tab20c_r;
            }
        }
        private static Gradient _tab20c_r;
            }
}