//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEngine;

namespace Chromatic {

    public static partial class ColorMaps {

        public static Texture2D magma {
            get {
                if (_magma == null) {
                    _magma = Resources.Load<Texture2D>("magma");
                }
                return _magma;
            }
        }
        private static Texture2D _magma;

        public static Texture2D inferno {
            get {
                if (_inferno == null) {
                    _inferno = Resources.Load<Texture2D>("inferno");
                }
                return _inferno;
            }
        }
        private static Texture2D _inferno;

        public static Texture2D plasma {
            get {
                if (_plasma == null) {
                    _plasma = Resources.Load<Texture2D>("plasma");
                }
                return _plasma;
            }
        }
        private static Texture2D _plasma;

        public static Texture2D viridis {
            get {
                if (_viridis == null) {
                    _viridis = Resources.Load<Texture2D>("viridis");
                }
                return _viridis;
            }
        }
        private static Texture2D _viridis;

        public static Texture2D cividis {
            get {
                if (_cividis == null) {
                    _cividis = Resources.Load<Texture2D>("cividis");
                }
                return _cividis;
            }
        }
        private static Texture2D _cividis;

        public static Texture2D twilight {
            get {
                if (_twilight == null) {
                    _twilight = Resources.Load<Texture2D>("twilight");
                }
                return _twilight;
            }
        }
        private static Texture2D _twilight;

        public static Texture2D twilight_shifted {
            get {
                if (_twilight_shifted == null) {
                    _twilight_shifted = Resources.Load<Texture2D>("twilight_shifted");
                }
                return _twilight_shifted;
            }
        }
        private static Texture2D _twilight_shifted;

        public static Texture2D turbo {
            get {
                if (_turbo == null) {
                    _turbo = Resources.Load<Texture2D>("turbo");
                }
                return _turbo;
            }
        }
        private static Texture2D _turbo;

        public static Texture2D Blues {
            get {
                if (_Blues == null) {
                    _Blues = Resources.Load<Texture2D>("Blues");
                }
                return _Blues;
            }
        }
        private static Texture2D _Blues;

        public static Texture2D BrBG {
            get {
                if (_BrBG == null) {
                    _BrBG = Resources.Load<Texture2D>("BrBG");
                }
                return _BrBG;
            }
        }
        private static Texture2D _BrBG;

        public static Texture2D BuGn {
            get {
                if (_BuGn == null) {
                    _BuGn = Resources.Load<Texture2D>("BuGn");
                }
                return _BuGn;
            }
        }
        private static Texture2D _BuGn;

        public static Texture2D BuPu {
            get {
                if (_BuPu == null) {
                    _BuPu = Resources.Load<Texture2D>("BuPu");
                }
                return _BuPu;
            }
        }
        private static Texture2D _BuPu;

        public static Texture2D CMRmap {
            get {
                if (_CMRmap == null) {
                    _CMRmap = Resources.Load<Texture2D>("CMRmap");
                }
                return _CMRmap;
            }
        }
        private static Texture2D _CMRmap;

        public static Texture2D GnBu {
            get {
                if (_GnBu == null) {
                    _GnBu = Resources.Load<Texture2D>("GnBu");
                }
                return _GnBu;
            }
        }
        private static Texture2D _GnBu;

        public static Texture2D Greens {
            get {
                if (_Greens == null) {
                    _Greens = Resources.Load<Texture2D>("Greens");
                }
                return _Greens;
            }
        }
        private static Texture2D _Greens;

        public static Texture2D Greys {
            get {
                if (_Greys == null) {
                    _Greys = Resources.Load<Texture2D>("Greys");
                }
                return _Greys;
            }
        }
        private static Texture2D _Greys;

        public static Texture2D OrRd {
            get {
                if (_OrRd == null) {
                    _OrRd = Resources.Load<Texture2D>("OrRd");
                }
                return _OrRd;
            }
        }
        private static Texture2D _OrRd;

        public static Texture2D Oranges {
            get {
                if (_Oranges == null) {
                    _Oranges = Resources.Load<Texture2D>("Oranges");
                }
                return _Oranges;
            }
        }
        private static Texture2D _Oranges;

        public static Texture2D PRGn {
            get {
                if (_PRGn == null) {
                    _PRGn = Resources.Load<Texture2D>("PRGn");
                }
                return _PRGn;
            }
        }
        private static Texture2D _PRGn;

        public static Texture2D PiYG {
            get {
                if (_PiYG == null) {
                    _PiYG = Resources.Load<Texture2D>("PiYG");
                }
                return _PiYG;
            }
        }
        private static Texture2D _PiYG;

        public static Texture2D PuBu {
            get {
                if (_PuBu == null) {
                    _PuBu = Resources.Load<Texture2D>("PuBu");
                }
                return _PuBu;
            }
        }
        private static Texture2D _PuBu;

        public static Texture2D PuBuGn {
            get {
                if (_PuBuGn == null) {
                    _PuBuGn = Resources.Load<Texture2D>("PuBuGn");
                }
                return _PuBuGn;
            }
        }
        private static Texture2D _PuBuGn;

        public static Texture2D PuOr {
            get {
                if (_PuOr == null) {
                    _PuOr = Resources.Load<Texture2D>("PuOr");
                }
                return _PuOr;
            }
        }
        private static Texture2D _PuOr;

        public static Texture2D PuRd {
            get {
                if (_PuRd == null) {
                    _PuRd = Resources.Load<Texture2D>("PuRd");
                }
                return _PuRd;
            }
        }
        private static Texture2D _PuRd;

        public static Texture2D Purples {
            get {
                if (_Purples == null) {
                    _Purples = Resources.Load<Texture2D>("Purples");
                }
                return _Purples;
            }
        }
        private static Texture2D _Purples;

        public static Texture2D RdBu {
            get {
                if (_RdBu == null) {
                    _RdBu = Resources.Load<Texture2D>("RdBu");
                }
                return _RdBu;
            }
        }
        private static Texture2D _RdBu;

        public static Texture2D RdGy {
            get {
                if (_RdGy == null) {
                    _RdGy = Resources.Load<Texture2D>("RdGy");
                }
                return _RdGy;
            }
        }
        private static Texture2D _RdGy;

        public static Texture2D RdPu {
            get {
                if (_RdPu == null) {
                    _RdPu = Resources.Load<Texture2D>("RdPu");
                }
                return _RdPu;
            }
        }
        private static Texture2D _RdPu;

        public static Texture2D RdYlBu {
            get {
                if (_RdYlBu == null) {
                    _RdYlBu = Resources.Load<Texture2D>("RdYlBu");
                }
                return _RdYlBu;
            }
        }
        private static Texture2D _RdYlBu;

        public static Texture2D RdYlGn {
            get {
                if (_RdYlGn == null) {
                    _RdYlGn = Resources.Load<Texture2D>("RdYlGn");
                }
                return _RdYlGn;
            }
        }
        private static Texture2D _RdYlGn;

        public static Texture2D Reds {
            get {
                if (_Reds == null) {
                    _Reds = Resources.Load<Texture2D>("Reds");
                }
                return _Reds;
            }
        }
        private static Texture2D _Reds;

        public static Texture2D Spectral {
            get {
                if (_Spectral == null) {
                    _Spectral = Resources.Load<Texture2D>("Spectral");
                }
                return _Spectral;
            }
        }
        private static Texture2D _Spectral;

        public static Texture2D Wistia {
            get {
                if (_Wistia == null) {
                    _Wistia = Resources.Load<Texture2D>("Wistia");
                }
                return _Wistia;
            }
        }
        private static Texture2D _Wistia;

        public static Texture2D YlGn {
            get {
                if (_YlGn == null) {
                    _YlGn = Resources.Load<Texture2D>("YlGn");
                }
                return _YlGn;
            }
        }
        private static Texture2D _YlGn;

        public static Texture2D YlGnBu {
            get {
                if (_YlGnBu == null) {
                    _YlGnBu = Resources.Load<Texture2D>("YlGnBu");
                }
                return _YlGnBu;
            }
        }
        private static Texture2D _YlGnBu;

        public static Texture2D YlOrBr {
            get {
                if (_YlOrBr == null) {
                    _YlOrBr = Resources.Load<Texture2D>("YlOrBr");
                }
                return _YlOrBr;
            }
        }
        private static Texture2D _YlOrBr;

        public static Texture2D YlOrRd {
            get {
                if (_YlOrRd == null) {
                    _YlOrRd = Resources.Load<Texture2D>("YlOrRd");
                }
                return _YlOrRd;
            }
        }
        private static Texture2D _YlOrRd;

        public static Texture2D afmhot {
            get {
                if (_afmhot == null) {
                    _afmhot = Resources.Load<Texture2D>("afmhot");
                }
                return _afmhot;
            }
        }
        private static Texture2D _afmhot;

        public static Texture2D autumn {
            get {
                if (_autumn == null) {
                    _autumn = Resources.Load<Texture2D>("autumn");
                }
                return _autumn;
            }
        }
        private static Texture2D _autumn;

        public static Texture2D binary {
            get {
                if (_binary == null) {
                    _binary = Resources.Load<Texture2D>("binary");
                }
                return _binary;
            }
        }
        private static Texture2D _binary;

        public static Texture2D bone {
            get {
                if (_bone == null) {
                    _bone = Resources.Load<Texture2D>("bone");
                }
                return _bone;
            }
        }
        private static Texture2D _bone;

        public static Texture2D brg {
            get {
                if (_brg == null) {
                    _brg = Resources.Load<Texture2D>("brg");
                }
                return _brg;
            }
        }
        private static Texture2D _brg;

        public static Texture2D bwr {
            get {
                if (_bwr == null) {
                    _bwr = Resources.Load<Texture2D>("bwr");
                }
                return _bwr;
            }
        }
        private static Texture2D _bwr;

        public static Texture2D cool {
            get {
                if (_cool == null) {
                    _cool = Resources.Load<Texture2D>("cool");
                }
                return _cool;
            }
        }
        private static Texture2D _cool;

        public static Texture2D coolwarm {
            get {
                if (_coolwarm == null) {
                    _coolwarm = Resources.Load<Texture2D>("coolwarm");
                }
                return _coolwarm;
            }
        }
        private static Texture2D _coolwarm;

        public static Texture2D copper {
            get {
                if (_copper == null) {
                    _copper = Resources.Load<Texture2D>("copper");
                }
                return _copper;
            }
        }
        private static Texture2D _copper;

        public static Texture2D cubehelix {
            get {
                if (_cubehelix == null) {
                    _cubehelix = Resources.Load<Texture2D>("cubehelix");
                }
                return _cubehelix;
            }
        }
        private static Texture2D _cubehelix;

        public static Texture2D flag {
            get {
                if (_flag == null) {
                    _flag = Resources.Load<Texture2D>("flag");
                }
                return _flag;
            }
        }
        private static Texture2D _flag;

        public static Texture2D gist_earth {
            get {
                if (_gist_earth == null) {
                    _gist_earth = Resources.Load<Texture2D>("gist_earth");
                }
                return _gist_earth;
            }
        }
        private static Texture2D _gist_earth;

        public static Texture2D gist_gray {
            get {
                if (_gist_gray == null) {
                    _gist_gray = Resources.Load<Texture2D>("gist_gray");
                }
                return _gist_gray;
            }
        }
        private static Texture2D _gist_gray;

        public static Texture2D gist_heat {
            get {
                if (_gist_heat == null) {
                    _gist_heat = Resources.Load<Texture2D>("gist_heat");
                }
                return _gist_heat;
            }
        }
        private static Texture2D _gist_heat;

        public static Texture2D gist_ncar {
            get {
                if (_gist_ncar == null) {
                    _gist_ncar = Resources.Load<Texture2D>("gist_ncar");
                }
                return _gist_ncar;
            }
        }
        private static Texture2D _gist_ncar;

        public static Texture2D gist_rainbow {
            get {
                if (_gist_rainbow == null) {
                    _gist_rainbow = Resources.Load<Texture2D>("gist_rainbow");
                }
                return _gist_rainbow;
            }
        }
        private static Texture2D _gist_rainbow;

        public static Texture2D gist_stern {
            get {
                if (_gist_stern == null) {
                    _gist_stern = Resources.Load<Texture2D>("gist_stern");
                }
                return _gist_stern;
            }
        }
        private static Texture2D _gist_stern;

        public static Texture2D gist_yarg {
            get {
                if (_gist_yarg == null) {
                    _gist_yarg = Resources.Load<Texture2D>("gist_yarg");
                }
                return _gist_yarg;
            }
        }
        private static Texture2D _gist_yarg;

        public static Texture2D gnuplot {
            get {
                if (_gnuplot == null) {
                    _gnuplot = Resources.Load<Texture2D>("gnuplot");
                }
                return _gnuplot;
            }
        }
        private static Texture2D _gnuplot;

        public static Texture2D gnuplot2 {
            get {
                if (_gnuplot2 == null) {
                    _gnuplot2 = Resources.Load<Texture2D>("gnuplot2");
                }
                return _gnuplot2;
            }
        }
        private static Texture2D _gnuplot2;

        public static Texture2D gray {
            get {
                if (_gray == null) {
                    _gray = Resources.Load<Texture2D>("gray");
                }
                return _gray;
            }
        }
        private static Texture2D _gray;

        public static Texture2D hot {
            get {
                if (_hot == null) {
                    _hot = Resources.Load<Texture2D>("hot");
                }
                return _hot;
            }
        }
        private static Texture2D _hot;

        public static Texture2D hsv {
            get {
                if (_hsv == null) {
                    _hsv = Resources.Load<Texture2D>("hsv");
                }
                return _hsv;
            }
        }
        private static Texture2D _hsv;

        public static Texture2D jet {
            get {
                if (_jet == null) {
                    _jet = Resources.Load<Texture2D>("jet");
                }
                return _jet;
            }
        }
        private static Texture2D _jet;

        public static Texture2D nipy_spectral {
            get {
                if (_nipy_spectral == null) {
                    _nipy_spectral = Resources.Load<Texture2D>("nipy_spectral");
                }
                return _nipy_spectral;
            }
        }
        private static Texture2D _nipy_spectral;

        public static Texture2D ocean {
            get {
                if (_ocean == null) {
                    _ocean = Resources.Load<Texture2D>("ocean");
                }
                return _ocean;
            }
        }
        private static Texture2D _ocean;

        public static Texture2D pink {
            get {
                if (_pink == null) {
                    _pink = Resources.Load<Texture2D>("pink");
                }
                return _pink;
            }
        }
        private static Texture2D _pink;

        public static Texture2D prism {
            get {
                if (_prism == null) {
                    _prism = Resources.Load<Texture2D>("prism");
                }
                return _prism;
            }
        }
        private static Texture2D _prism;

        public static Texture2D rainbow {
            get {
                if (_rainbow == null) {
                    _rainbow = Resources.Load<Texture2D>("rainbow");
                }
                return _rainbow;
            }
        }
        private static Texture2D _rainbow;

        public static Texture2D seismic {
            get {
                if (_seismic == null) {
                    _seismic = Resources.Load<Texture2D>("seismic");
                }
                return _seismic;
            }
        }
        private static Texture2D _seismic;

        public static Texture2D spring {
            get {
                if (_spring == null) {
                    _spring = Resources.Load<Texture2D>("spring");
                }
                return _spring;
            }
        }
        private static Texture2D _spring;

        public static Texture2D summer {
            get {
                if (_summer == null) {
                    _summer = Resources.Load<Texture2D>("summer");
                }
                return _summer;
            }
        }
        private static Texture2D _summer;

        public static Texture2D terrain {
            get {
                if (_terrain == null) {
                    _terrain = Resources.Load<Texture2D>("terrain");
                }
                return _terrain;
            }
        }
        private static Texture2D _terrain;

        public static Texture2D winter {
            get {
                if (_winter == null) {
                    _winter = Resources.Load<Texture2D>("winter");
                }
                return _winter;
            }
        }
        private static Texture2D _winter;

        public static Texture2D Accent {
            get {
                if (_Accent == null) {
                    _Accent = Resources.Load<Texture2D>("Accent");
                }
                return _Accent;
            }
        }
        private static Texture2D _Accent;

        public static Texture2D Dark2 {
            get {
                if (_Dark2 == null) {
                    _Dark2 = Resources.Load<Texture2D>("Dark2");
                }
                return _Dark2;
            }
        }
        private static Texture2D _Dark2;

        public static Texture2D Paired {
            get {
                if (_Paired == null) {
                    _Paired = Resources.Load<Texture2D>("Paired");
                }
                return _Paired;
            }
        }
        private static Texture2D _Paired;

        public static Texture2D Pastel1 {
            get {
                if (_Pastel1 == null) {
                    _Pastel1 = Resources.Load<Texture2D>("Pastel1");
                }
                return _Pastel1;
            }
        }
        private static Texture2D _Pastel1;

        public static Texture2D Pastel2 {
            get {
                if (_Pastel2 == null) {
                    _Pastel2 = Resources.Load<Texture2D>("Pastel2");
                }
                return _Pastel2;
            }
        }
        private static Texture2D _Pastel2;

        public static Texture2D Set1 {
            get {
                if (_Set1 == null) {
                    _Set1 = Resources.Load<Texture2D>("Set1");
                }
                return _Set1;
            }
        }
        private static Texture2D _Set1;

        public static Texture2D Set2 {
            get {
                if (_Set2 == null) {
                    _Set2 = Resources.Load<Texture2D>("Set2");
                }
                return _Set2;
            }
        }
        private static Texture2D _Set2;

        public static Texture2D Set3 {
            get {
                if (_Set3 == null) {
                    _Set3 = Resources.Load<Texture2D>("Set3");
                }
                return _Set3;
            }
        }
        private static Texture2D _Set3;

        public static Texture2D tab10 {
            get {
                if (_tab10 == null) {
                    _tab10 = Resources.Load<Texture2D>("tab10");
                }
                return _tab10;
            }
        }
        private static Texture2D _tab10;

        public static Texture2D tab20 {
            get {
                if (_tab20 == null) {
                    _tab20 = Resources.Load<Texture2D>("tab20");
                }
                return _tab20;
            }
        }
        private static Texture2D _tab20;

        public static Texture2D tab20b {
            get {
                if (_tab20b == null) {
                    _tab20b = Resources.Load<Texture2D>("tab20b");
                }
                return _tab20b;
            }
        }
        private static Texture2D _tab20b;

        public static Texture2D tab20c {
            get {
                if (_tab20c == null) {
                    _tab20c = Resources.Load<Texture2D>("tab20c");
                }
                return _tab20c;
            }
        }
        private static Texture2D _tab20c;
    }
}