/*
 * ----------------------------------------------------------------
 * <auto-generated>
 * This file is auto-generated and should not be modified manually.
 * </auto-generated>
 * ----------------------------------------------------------------
 */

using UnityEngine;

namespace Chromatic {

    public static partial class ColorMaps {

        public static Texture2D magma => _magma ?? (_magma = Resources.Load<Texture2D>("magma"));
        private static Texture2D _magma;

        public static Texture2D inferno => _inferno ?? (_inferno = Resources.Load<Texture2D>("inferno"));
        private static Texture2D _inferno;

        public static Texture2D plasma => _plasma ?? (_plasma = Resources.Load<Texture2D>("plasma"));
        private static Texture2D _plasma;

        public static Texture2D viridis => _viridis ?? (_viridis = Resources.Load<Texture2D>("viridis"));
        private static Texture2D _viridis;

        public static Texture2D cividis => _cividis ?? (_cividis = Resources.Load<Texture2D>("cividis"));
        private static Texture2D _cividis;

        public static Texture2D twilight => _twilight ?? (_twilight = Resources.Load<Texture2D>("twilight"));
        private static Texture2D _twilight;

        public static Texture2D twilight_shifted => _twilight_shifted ?? (_twilight_shifted = Resources.Load<Texture2D>("twilight_shifted"));
        private static Texture2D _twilight_shifted;

        public static Texture2D turbo => _turbo ?? (_turbo = Resources.Load<Texture2D>("turbo"));
        private static Texture2D _turbo;

        public static Texture2D Blues => _Blues ?? (_Blues = Resources.Load<Texture2D>("Blues"));
        private static Texture2D _Blues;

        public static Texture2D BrBG => _BrBG ?? (_BrBG = Resources.Load<Texture2D>("BrBG"));
        private static Texture2D _BrBG;

        public static Texture2D BuGn => _BuGn ?? (_BuGn = Resources.Load<Texture2D>("BuGn"));
        private static Texture2D _BuGn;

        public static Texture2D BuPu => _BuPu ?? (_BuPu = Resources.Load<Texture2D>("BuPu"));
        private static Texture2D _BuPu;

        public static Texture2D CMRmap => _CMRmap ?? (_CMRmap = Resources.Load<Texture2D>("CMRmap"));
        private static Texture2D _CMRmap;

        public static Texture2D GnBu => _GnBu ?? (_GnBu = Resources.Load<Texture2D>("GnBu"));
        private static Texture2D _GnBu;

        public static Texture2D Greens => _Greens ?? (_Greens = Resources.Load<Texture2D>("Greens"));
        private static Texture2D _Greens;

        public static Texture2D Greys => _Greys ?? (_Greys = Resources.Load<Texture2D>("Greys"));
        private static Texture2D _Greys;

        public static Texture2D OrRd => _OrRd ?? (_OrRd = Resources.Load<Texture2D>("OrRd"));
        private static Texture2D _OrRd;

        public static Texture2D Oranges => _Oranges ?? (_Oranges = Resources.Load<Texture2D>("Oranges"));
        private static Texture2D _Oranges;

        public static Texture2D PRGn => _PRGn ?? (_PRGn = Resources.Load<Texture2D>("PRGn"));
        private static Texture2D _PRGn;

        public static Texture2D PiYG => _PiYG ?? (_PiYG = Resources.Load<Texture2D>("PiYG"));
        private static Texture2D _PiYG;

        public static Texture2D PuBu => _PuBu ?? (_PuBu = Resources.Load<Texture2D>("PuBu"));
        private static Texture2D _PuBu;

        public static Texture2D PuBuGn => _PuBuGn ?? (_PuBuGn = Resources.Load<Texture2D>("PuBuGn"));
        private static Texture2D _PuBuGn;

        public static Texture2D PuOr => _PuOr ?? (_PuOr = Resources.Load<Texture2D>("PuOr"));
        private static Texture2D _PuOr;

        public static Texture2D PuRd => _PuRd ?? (_PuRd = Resources.Load<Texture2D>("PuRd"));
        private static Texture2D _PuRd;

        public static Texture2D Purples => _Purples ?? (_Purples = Resources.Load<Texture2D>("Purples"));
        private static Texture2D _Purples;

        public static Texture2D RdBu => _RdBu ?? (_RdBu = Resources.Load<Texture2D>("RdBu"));
        private static Texture2D _RdBu;

        public static Texture2D RdGy => _RdGy ?? (_RdGy = Resources.Load<Texture2D>("RdGy"));
        private static Texture2D _RdGy;

        public static Texture2D RdPu => _RdPu ?? (_RdPu = Resources.Load<Texture2D>("RdPu"));
        private static Texture2D _RdPu;

        public static Texture2D RdYlBu => _RdYlBu ?? (_RdYlBu = Resources.Load<Texture2D>("RdYlBu"));
        private static Texture2D _RdYlBu;

        public static Texture2D RdYlGn => _RdYlGn ?? (_RdYlGn = Resources.Load<Texture2D>("RdYlGn"));
        private static Texture2D _RdYlGn;

        public static Texture2D Reds => _Reds ?? (_Reds = Resources.Load<Texture2D>("Reds"));
        private static Texture2D _Reds;

        public static Texture2D Spectral => _Spectral ?? (_Spectral = Resources.Load<Texture2D>("Spectral"));
        private static Texture2D _Spectral;

        public static Texture2D Wistia => _Wistia ?? (_Wistia = Resources.Load<Texture2D>("Wistia"));
        private static Texture2D _Wistia;

        public static Texture2D YlGn => _YlGn ?? (_YlGn = Resources.Load<Texture2D>("YlGn"));
        private static Texture2D _YlGn;

        public static Texture2D YlGnBu => _YlGnBu ?? (_YlGnBu = Resources.Load<Texture2D>("YlGnBu"));
        private static Texture2D _YlGnBu;

        public static Texture2D YlOrBr => _YlOrBr ?? (_YlOrBr = Resources.Load<Texture2D>("YlOrBr"));
        private static Texture2D _YlOrBr;

        public static Texture2D YlOrRd => _YlOrRd ?? (_YlOrRd = Resources.Load<Texture2D>("YlOrRd"));
        private static Texture2D _YlOrRd;

        public static Texture2D afmhot => _afmhot ?? (_afmhot = Resources.Load<Texture2D>("afmhot"));
        private static Texture2D _afmhot;

        public static Texture2D autumn => _autumn ?? (_autumn = Resources.Load<Texture2D>("autumn"));
        private static Texture2D _autumn;

        public static Texture2D binary => _binary ?? (_binary = Resources.Load<Texture2D>("binary"));
        private static Texture2D _binary;

        public static Texture2D bone => _bone ?? (_bone = Resources.Load<Texture2D>("bone"));
        private static Texture2D _bone;

        public static Texture2D brg => _brg ?? (_brg = Resources.Load<Texture2D>("brg"));
        private static Texture2D _brg;

        public static Texture2D bwr => _bwr ?? (_bwr = Resources.Load<Texture2D>("bwr"));
        private static Texture2D _bwr;

        public static Texture2D cool => _cool ?? (_cool = Resources.Load<Texture2D>("cool"));
        private static Texture2D _cool;

        public static Texture2D coolwarm => _coolwarm ?? (_coolwarm = Resources.Load<Texture2D>("coolwarm"));
        private static Texture2D _coolwarm;

        public static Texture2D copper => _copper ?? (_copper = Resources.Load<Texture2D>("copper"));
        private static Texture2D _copper;

        public static Texture2D cubehelix => _cubehelix ?? (_cubehelix = Resources.Load<Texture2D>("cubehelix"));
        private static Texture2D _cubehelix;

        public static Texture2D flag => _flag ?? (_flag = Resources.Load<Texture2D>("flag"));
        private static Texture2D _flag;

        public static Texture2D gist_earth => _gist_earth ?? (_gist_earth = Resources.Load<Texture2D>("gist_earth"));
        private static Texture2D _gist_earth;

        public static Texture2D gist_gray => _gist_gray ?? (_gist_gray = Resources.Load<Texture2D>("gist_gray"));
        private static Texture2D _gist_gray;

        public static Texture2D gist_heat => _gist_heat ?? (_gist_heat = Resources.Load<Texture2D>("gist_heat"));
        private static Texture2D _gist_heat;

        public static Texture2D gist_ncar => _gist_ncar ?? (_gist_ncar = Resources.Load<Texture2D>("gist_ncar"));
        private static Texture2D _gist_ncar;

        public static Texture2D gist_rainbow => _gist_rainbow ?? (_gist_rainbow = Resources.Load<Texture2D>("gist_rainbow"));
        private static Texture2D _gist_rainbow;

        public static Texture2D gist_stern => _gist_stern ?? (_gist_stern = Resources.Load<Texture2D>("gist_stern"));
        private static Texture2D _gist_stern;

        public static Texture2D gist_yarg => _gist_yarg ?? (_gist_yarg = Resources.Load<Texture2D>("gist_yarg"));
        private static Texture2D _gist_yarg;

        public static Texture2D gnuplot => _gnuplot ?? (_gnuplot = Resources.Load<Texture2D>("gnuplot"));
        private static Texture2D _gnuplot;

        public static Texture2D gnuplot2 => _gnuplot2 ?? (_gnuplot2 = Resources.Load<Texture2D>("gnuplot2"));
        private static Texture2D _gnuplot2;

        public static Texture2D gray => _gray ?? (_gray = Resources.Load<Texture2D>("gray"));
        private static Texture2D _gray;

        public static Texture2D hot => _hot ?? (_hot = Resources.Load<Texture2D>("hot"));
        private static Texture2D _hot;

        public static Texture2D hsv => _hsv ?? (_hsv = Resources.Load<Texture2D>("hsv"));
        private static Texture2D _hsv;

        public static Texture2D jet => _jet ?? (_jet = Resources.Load<Texture2D>("jet"));
        private static Texture2D _jet;

        public static Texture2D nipy_spectral => _nipy_spectral ?? (_nipy_spectral = Resources.Load<Texture2D>("nipy_spectral"));
        private static Texture2D _nipy_spectral;

        public static Texture2D ocean => _ocean ?? (_ocean = Resources.Load<Texture2D>("ocean"));
        private static Texture2D _ocean;

        public static Texture2D pink => _pink ?? (_pink = Resources.Load<Texture2D>("pink"));
        private static Texture2D _pink;

        public static Texture2D prism => _prism ?? (_prism = Resources.Load<Texture2D>("prism"));
        private static Texture2D _prism;

        public static Texture2D rainbow => _rainbow ?? (_rainbow = Resources.Load<Texture2D>("rainbow"));
        private static Texture2D _rainbow;

        public static Texture2D seismic => _seismic ?? (_seismic = Resources.Load<Texture2D>("seismic"));
        private static Texture2D _seismic;

        public static Texture2D spring => _spring ?? (_spring = Resources.Load<Texture2D>("spring"));
        private static Texture2D _spring;

        public static Texture2D summer => _summer ?? (_summer = Resources.Load<Texture2D>("summer"));
        private static Texture2D _summer;

        public static Texture2D terrain => _terrain ?? (_terrain = Resources.Load<Texture2D>("terrain"));
        private static Texture2D _terrain;

        public static Texture2D winter => _winter ?? (_winter = Resources.Load<Texture2D>("winter"));
        private static Texture2D _winter;

        public static Texture2D Accent => _Accent ?? (_Accent = Resources.Load<Texture2D>("Accent"));
        private static Texture2D _Accent;

        public static Texture2D Dark2 => _Dark2 ?? (_Dark2 = Resources.Load<Texture2D>("Dark2"));
        private static Texture2D _Dark2;

        public static Texture2D Paired => _Paired ?? (_Paired = Resources.Load<Texture2D>("Paired"));
        private static Texture2D _Paired;

        public static Texture2D Pastel1 => _Pastel1 ?? (_Pastel1 = Resources.Load<Texture2D>("Pastel1"));
        private static Texture2D _Pastel1;

        public static Texture2D Pastel2 => _Pastel2 ?? (_Pastel2 = Resources.Load<Texture2D>("Pastel2"));
        private static Texture2D _Pastel2;

        public static Texture2D Set1 => _Set1 ?? (_Set1 = Resources.Load<Texture2D>("Set1"));
        private static Texture2D _Set1;

        public static Texture2D Set2 => _Set2 ?? (_Set2 = Resources.Load<Texture2D>("Set2"));
        private static Texture2D _Set2;

        public static Texture2D Set3 => _Set3 ?? (_Set3 = Resources.Load<Texture2D>("Set3"));
        private static Texture2D _Set3;

        public static Texture2D tab10 => _tab10 ?? (_tab10 = Resources.Load<Texture2D>("tab10"));
        private static Texture2D _tab10;

        public static Texture2D tab20 => _tab20 ?? (_tab20 = Resources.Load<Texture2D>("tab20"));
        private static Texture2D _tab20;

        public static Texture2D tab20b => _tab20b ?? (_tab20b = Resources.Load<Texture2D>("tab20b"));
        private static Texture2D _tab20b;

        public static Texture2D tab20c => _tab20c ?? (_tab20c = Resources.Load<Texture2D>("tab20c"));
        private static Texture2D _tab20c;
    }
}